In [ ]:
import numpy as np
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [ ]:
arr=np.array([1,2,3])
print(arr.dtype)
new_arr=arr.astype('f')
print(new_arr.dtype)

int64
float32


In [ ]:
arr=np.array([1.,2.2,3.3])
print(arr.dtype)
new_arr=arr.astype('i')
print(new_arr.dtype)

float64
int32


In [ ]:
arr=np.array(['1.','2.2','-3.3'])
print(arr.dtype)
new_arr=arr.astype('f')
print(new_arr.dtype)

<U4
float32


In [ ]:
arr=np.array(['1.','2.2','abc'])
print(arr.dtype)
try:
  new_arr=arr.astype('f')
  print(new_arr.dtype)
except ValueError as e:
  print("Conversion failed:",e)


<U3
Conversion failed: could not convert string to float: np.str_('abc')


In [ ]:
arr1=np.arange(10)
arr2=np.random.randn(10)
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)
new_arr=arr1.astype(arr2.dtype)
print(new_arr,new_arr.dtype)

[0 1 2 3 4 5 6 7 8 9] int64
[-1.19431344 -1.02155881  0.04153329 -1.13039838 -1.011223    0.7073836
 -1.34964995  0.68828792 -0.38505886 -1.79745114] float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[0 1 2 3 4 5 6 7 8 9] int64
[ 0.77341127 -0.75013673 -1.84035724 -1.24143852  1.06114628  0.51064573
 -0.00300883  2.88272129  1.55149353 -0.75319779] float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [ ]:
str_array=np.array(['hi','bye'])
print(str_array)

['hi' 'bye']


In [ ]:
a=np.array([[1,2],[3,4,5]])
b=np.array([4,5,6,7])
print(a+b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
arr=np.arange(12)
new_arr=arr.reshape(4,3)
print(new_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
arr=np.arange(12)
new_arr=arr.reshape(4,3,order='F')
print(new_arr)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
arr=np.arange(12)
new_arr=arr.reshape(4,3,order='c')
print(new_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
arr = np.array([[1, 2, 3, 4,9,10], [5, 6, 7, 8,11,12]])
print(arr)
new_arr=arr.reshape(3,2,2)
print(new_arr)

[[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]


In [ ]:
arr=np.array([[10,20],[30,40]])
print(arr)
flat_arr=arr.flatten()
flat_arr[0]=55
print(flat_arr)
rav_arr=arr.ravel()
rav_arr[0]=22
print(rav_arr)

[[10 20]
 [30 40]]
[55 20 30 40]
[22 20 30 40]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
r_arr=np.ravel(arr)
r_arr[0]=10
print(r_arr)
print(arr)
f_arr=arr.flatten()
f_arr[0]=44
print(f_arr)
print(arr)

[[1 2 3]
 [4 5 6]]
[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]
[44  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]


In [ ]:
arr=np.arange(15)
arr.reshape((5,-1))
o_arr=np.ones((3,5))
arr.reshape(o_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x=np.arange(10)
print(x[:5])
print(x[5:])
print(x[4:7])

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]


In [ ]:
print(x[::2])
print(x[1::2])

[0 2 4 6 8]
[1 3 5 7 9]


In [ ]:
print(x[5::-1])

[5 4 3 2 1 0]


In [ ]:
x=np.arange(10)
x[5:]=2
print(x)
x[::2]=100
print(x)


[0 1 2 3 4 2 2 2 2 2]
[100   1 100   3 100   2 100   2 100   2]


In [ ]:
arr=np.arange(10)
x_copy=x[2:7].copy()
x_copy[:]=100
print(x_copy)
print(x)

[100 100 100 100 100]
[100   1 100   3 100   2 100   2 100   2]


In [ ]:
x2 = np.array([[12, 5, 2, 4],
[ 7, 6, 8, 8],
[ 1, 6, 7, 7]])
new_x2=x2.copy()
new_x2[0]=10
print(new_x2)
print(x2)

[[10 10 10 10]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
x2 = np.array([[12, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
print(x2)
print(x2[::2,::2])

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[12  2]
 [ 1  7]]


In [ ]:
x=np.arange(24).reshape(2,3,4)
print(x)
print(x[...,2])
print(x[:,:,2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 2  6 10]
 [14 18 22]]
[[ 2  6 10]
 [14 18 22]]


In [ ]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
print(x2[1,:2])

[7 6]


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(28).reshape(7, 4)
print(data)
print(names=='Bob')
data[names!='Bob']=-1
print(data)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[ True False False  True False False False]
[[ 0  1  2  3]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [12 13 14 15]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [ ]:
names = np.array(['Alice', 'Bob', 'Charlie', 'David'])
ages = np.array([25.5, 30, 28.2, 35])
ot_29=ages>29
print(names[ot_29])
c=(names=='Alice') | (names=='David')
print(ages[c])

['Bob' 'David']
[25.5 35. ]


In [ ]:
city_names = np.array(['New York', 'Los Angeles', 'Chicago', 'Houston'])
temperatures = np.array([-25, 32, -28, 35])
neg_temp=temperatures<0
print(city_names[neg_temp])
temperatures[neg_temp]=0
print(temperatures)

['New York' 'Chicago']
[ 0 32  0 35]


In [ ]:
arr=np.arange(12).reshape(3,4)
print(arr)
print(arr.T)
print(np.transpose(arr.T))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
import numpy as np
arr1=np.transpose(arr,(1,0))
print(arr1)
arr2=np.transpose(arr,(0,1))
print(arr2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr=np.arange(12).reshape((2,3,2))
print(arr)
arr3=arr.T
print(arr3)
print(arr3.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
(2, 3, 2)


In [ ]:
arr=np.arange(12).reshape((3,4))
print(np.dot(arr,arr.T))
print(np.swapaxes(arr,0,1))

[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.multiply(arr1,arr2)
print(result)
res=np.matmul(arr1,arr2)
print(res)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
result=np.dot(arr1,arr2)
print(result)

[[19 22]
 [43 50]]


In [ ]:
import pandas as pd
dataset={
    'cars':["BMW","Volvo","Rolls Royce"],
    'passings':[3,4,5]
}
data=pd.DataFrame(dataset)
print(data)

          cars  passings
0          BMW         3
1        Volvo         4
2  Rolls Royce         5


In [ ]:
data=[10,20,30,40,50]
series=pd.Series(data)
print(series)
print(series.values)
print(series.index)

0    10
1    20
2    30
3    40
4    50
dtype: int64
[10 20 30 40 50]
RangeIndex(start=0, stop=5, step=1)


In [ ]:
a=[1,2,3]
var=pd.Series(a,index=['x','y','z'])
print(var)

x    1
y    2
z    3
dtype: int64


In [ ]:
a=[10,20,30,40,50]
index=['a','b','c','d','e']
val=pd.Series(a,index=index)
print(val)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [ ]:
print(val['b'])
print(val[['a','c','e']])

20
a    10
c    30
e    50
dtype: int64


In [ ]:
gt=val>25
print(gt)
print(val[val>25])
print(val*2)
print(np.sqrt(val))

a    False
b    False
c     True
d     True
e     True
dtype: bool
c    30
d    40
e    50
dtype: int64
a     20
b     40
c     60
d     80
e    100
dtype: int64
a    3.162278
b    4.472136
c    5.477226
d    6.324555
e    7.071068
dtype: float64


In [ ]:
population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}
population=pd.Series(population_dict)
print(population)
print('California' in population)
print('Italy' in population)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64
True
False


In [ ]:
import pandas as pd
import numpy as np
data=[10,np.nan,30,np.nan,40]
index=['a','b','c','d','e']
series=pd.Series(data,index=index)
print(series)
print(series.isnull())
print(series.notnull())

a    10.0
b     NaN
c    30.0
d     NaN
e    40.0
dtype: float64
a    False
b     True
c    False
d     True
e    False
dtype: bool
a     True
b    False
c     True
d    False
e     True
dtype: bool


In [ ]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
              'Florida': 170312, 'Illinois': 149995, 'North Carolina':123456}
area = pd.Series(area_dict)
print(area)
pop_den=population/area
print(pop_den)

California        423967
Texas             695662
New York          141297
Florida           170312
Illinois          149995
North Carolina    123456
dtype: int64
California         90.413926
Florida           114.806121
Illinois           85.883763
New York          139.076746
North Carolina           NaN
Texas              38.018740
dtype: float64


In [ ]:
male_population_dict = {'California': 19000000, 'Texas': 13000000, 'New York': 9500000,
                        'Florida': 9600000, 'Illinois': 6300000}
female_population_dict = {'California': 19332521, 'Texas': 13448193, 'New York':1953367,
                           'Florida': 9952860, 'Illinois': 6582135}
male_population = pd.Series(male_population_dict)
female_population = pd.Series(female_population_dict)
tot_pop=male_population+female_population
print(tot_pop)

California    38332521
Texas         26448193
New York      11453367
Florida       19552860
Illinois      12882135
dtype: int64


In [ ]:
subject1 = pd.Series([80, 75, 92, 68, 70, 95, 88], index=['Student 1', 'Student 2','Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7'])
subject2 = pd.Series([72, 88, 79, 91, 65, 82, 76], index=['Student 1', 'Student 2','Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7'])
subject3 = pd.Series([90, 68, 85, 73, 78, 92, 80], index=['Student 1', 'Student 2','Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7'])
subject4 = pd.Series([65, 92, 82, 88, 75, 79, 85], index=['Student 1', 'Student 2','Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7'])
subject5 = pd.Series([78, 70, 95, 62, 83, 86, 91], index=['Student 1', 'Student 2','Student 3', 'Student 4', 'Student 5', 'Student 6', 'Student 7'])
total_marks=subject1+subject2+subject3+subject4+subject5
for i in total_marks.index:
  print(i,total_marks[i])

Student 1 385
Student 2 393
Student 3 433
Student 4 382
Student 5 371
Student 6 434
Student 7 420


In [ ]:
data={
    "Calories":[420,330,790],
    "duration":[20,40,70]
}
df=pd.DataFrame(data)
print(df)

   Calories  duration
0       420        20
1       330        40
2       790        70


In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
         'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df=pd.DataFrame(data)
print(df)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2


In [ ]:
frame=pd.DataFrame(data,columns=['year','state','pop'])
print(frame)

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2


In [ ]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])
print(frame2)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN


In [ ]:
print(frame2['year'])
print(frame2['state'])
print(frame2.state)

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64
one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object
one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object


In [ ]:
print(frame2.loc['one'])
print(frame2.loc['three'])

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object
year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object


In [ ]:
frame2['debt']=12.4
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5  12.4
two    2001    Ohio  1.7  12.4
three  2002    Ohio  3.6  12.4
four   2001  Nevada  2.4  12.4
five   2002  Nevada  2.9  12.4
six    2003  Nevada  3.2  12.4


In [ ]:
frame2['debt']=np.arange(6)
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5


In [ ]:
val=pd.Series([1.2,2.3,3.3],index=['two','three','four'])
frame2['debt']=val
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7   1.2
three  2002    Ohio  3.6   2.3
four   2001  Nevada  2.4   3.3
five   2002  Nevada  2.9   NaN
six    2003  Nevada  3.2   NaN


In [ ]:
frame2['eastern']=frame2.state=='Ohio'
print(frame2)

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7   1.2     True
three  2002    Ohio  3.6   2.3     True
four   2001  Nevada  2.4   3.3    False
five   2002  Nevada  2.9   NaN    False
six    2003  Nevada  3.2   NaN    False


In [ ]:
frame4=pd.DataFrame({'nevada':{2001:2.4,2002:2.9},
     'Ohio':{2000:1.8,2001:2.3,2002:3.5}})
print(frame4)

      nevada  Ohio
2001     2.4   2.3
2002     2.9   3.5
2000     NaN   1.8


In [ ]:
frame5=pd.DataFrame(frame4,index=[2000,2001,2002,2003])
print(frame5)

      nevada  Ohio
2000     NaN   1.8
2001     2.4   2.3
2002     2.9   3.5
2003     NaN   NaN


In [ ]:
print(frame5.T)

        2000  2001  2002  2003
nevada   NaN   2.4   2.9   NaN
Ohio     1.8   2.3   3.5   NaN


In [ ]:
pdata=pd.DataFrame({'Ohio':frame4['Ohio'][:-1],
       'nevada':frame4['nevada'][:2]})
print(pdata)

      Ohio  nevada
2001   2.3     2.4
2002   3.5     2.9


In [ ]:
data=np.arange(9).reshape(3,3)
index=['Ohio','nevada','new york']
columns=['one','two','three']
df=pd.DataFrame(data, index=index, columns=columns)
df.index.name='state'
df.columns.name='number'
print(df)

number    one  two  three
state                    
Ohio        0    1      2
nevada      3    4      5
new york    6    7      8


In [ ]:
s=pd.Series(np.arange(5),index=['a','b','c','d','e'])
print(s)

print(s.index)
print(s.values)
print(s.index.values)
print(s.index.is_monotonic_increasing)
print(s.index.is_monotonic_decreasing)
print(s.index.is_unique)

print(s.index.get_loc('b'))
print(s['a':'d'])
print(s[['a','d']])

a    0
b    1
c    2
d    3
e    4
dtype: int64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[0 1 2 3 4]
['a' 'b' 'c' 'd' 'e']
True
False
True
1
a    0
b    1
c    2
d    3
dtype: int64
a    0
d    3
dtype: int64


In [ ]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
print(obj)
obj2=obj.reindex(['a','b','c','d','e'])
print(obj2)

df=pd.DataFrame(np.arange(9).reshape(3,3),index=['a','c','d'],columns=['Ohio','Texas','California'])
df2=df.reindex(columns=['Texas','Utah','California'])
print(df2)

df3=df.reindex(index=['a','b','c','d'],columns=['Dallas', 'Texas', 'Utah','California'])
print(df3)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64
   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8
   Dallas  Texas  Utah  California
a     NaN    1.0   NaN         2.0
b     NaN    NaN   NaN         NaN
c     NaN    4.0   NaN         5.0
d     NaN    7.0   NaN         8.0


In [ ]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
print(obj3)
obj4=obj3.reindex(range(6),method='ffill')
print(obj4)

0      blue
2    purple
4    yellow
dtype: object
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object


In [ ]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj4=obj3.reindex(range(6),method='ffill')
print(obj4)

obj5=obj3.reindex(range(6),method='bfill')
print(obj5)

obj6=obj3.reindex(range(6),fill_value='red')
print(obj6)

obj7=obj3.reindex(range(9),method='ffill',limit=1)
print(obj7)

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object
0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object
0      blue
1       red
2    purple
3       red
4    yellow
5       red
dtype: object
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
6       NaN
7       NaN
8       NaN
dtype: object


In [ ]:
arrays = [['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]
tuples=list(zip(*arrays))
index=pd.MultiIndex.from_tuples(tuples,names=['first','second'])
df=pd.DataFrame(np.random.randn(8,2),index=index,columns=['A','B'])
df.reindex(['bar', 'baz', 'foo', 'qux'],level='first')
print(df)

                     A         B
first second                    
bar   one    -0.343197  0.633388
      two     1.422590  0.726679
baz   one     1.193578 -0.581503
      two     0.368176 -0.099904
foo   one    -0.327031 -0.523504
      two    -0.342861 -1.915066
qux   one     0.561420  1.058808
      two    -0.014934  0.656986


In [ ]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj=obj.drop('c')
print(new_obj)


a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64


In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Dallas', 'NJ', 'New York'],
columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Dallas      4    5      6     7
NJ          8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop('three',axis=1)

one  two  four
Ohio        0    1     3
Dallas      4    5     7
NJ          8    9    11
New York   12   13    15

In [ ]:
data.drop(['Ohio'], inplace=True)
print(data)

          one  two  three  four
New York   12   13     14    15


In [ ]:
data = pd.DataFrame(np.arange(24).reshape((6, 4)),
          index=['Ohio', 'Dallas', 'Boston', 'NJ', 'New York', 'Austin'],
          columns=['one', 'two', 'three', 'four'])
print(data)

          one  two  three  four
Ohio        0    1      2     3
Dallas      4    5      6     7
Boston      8    9     10    11
NJ         12   13     14    15
New York   16   17     18    19
Austin     20   21     22    23


In [ ]:
print(data.three>5)
data[data.three>5]

Ohio        False
Dallas       True
Boston       True
NJ           True
New York     True
Austin       True
Name: three, dtype: bool


one  two  three  four
Dallas      4    5      6     7
Boston      8    9     10    11
NJ         12   13     14    15
New York   16   17     18    19
Austin     20   21     22    23

In [ ]:
data[data<5]=0
print(data)

          one  two  three  four
Ohio        0    0      0     0
Dallas      0    5      6     7
Boston      8    9     10    11
NJ         12   13     14    15
New York   16   17     18    19
Austin     20   21     22    23


In [ ]:
df1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df2=pd.DataFrame({'A':[7,8,9],'B':[10,11,12]})
print(df1)
print(df2)
print(df1+df2)
print(df1-df2)
print(df1*df2)
print(df1/df2)

   A  B
0  1  4
1  2  5
2  3  6
   A   B
0  7  10
1  8  11
2  9  12
    A   B
0   8  14
1  10  16
2  12  18
   A  B
0 -6 -6
1 -6 -6
2 -6 -6
    A   B
0   7  40
1  16  55
2  27  72
          A         B
0  0.142857  0.400000
1  0.250000  0.454545
2  0.333333  0.500000


In [ ]:
# Sample DataFrames with different indices and columns
df3 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=[0, 1, 2])
df4 = pd.DataFrame({'B': [7, 8, 9], 'C': [10, 11, 12]}, index=[1, 2, 3])
print(df3)
print(df4)

   A  B
0  1  4
1  2  5
2  3  6
   B   C
1  7  10
2  8  11
3  9  12


In [ ]:
result=df3.add(df4,fill_value=0)
print(result)

     A     B     C
0  1.0   4.0   NaN
1  2.0  12.0  10.0
2  3.0  14.0  11.0
3  NaN   9.0  12.0


In [ ]:
result=df3.radd(df4,fill_value=0)
print(result)

     A     B     C
0  1.0   4.0   NaN
1  2.0  12.0  10.0
2  3.0  14.0  11.0
3  NaN   9.0  12.0


In [ ]:
import numpy as np
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(frame)
print(np.abs(frame))

               b         d         e
Utah    0.714934  0.379138 -0.746550
Ohio   -0.485018 -2.229938  0.467657
Texas   1.527350  0.289510 -1.307950
Oregon  0.216316  0.728047  1.501404
               b         d         e
Utah    0.714934  0.379138  0.746550
Ohio    0.485018  2.229938  0.467657
Texas   1.527350  0.289510  1.307950
Oregon  0.216316  0.728047  1.501404


In [ ]:
f=lambda x:x.max()-x.min()
df_apply=frame.apply(f)
print(df_apply)
df_apply_axis=frame.apply(f,axis=1)
print(df_apply_axis)

b    2.012367
d    2.957985
e    2.809354
dtype: float64
Utah      1.461484
Ohio      2.697594
Texas     2.835300
Oregon    1.285088
dtype: float64


In [ ]:
import numpy as np
import pandas as pd
def f(x):
  return pd.Series([x.min(),x.max()],index=['min','max'])
df_apply_series=frame.apply(f)
print(df_apply_series)

            b         d         e
min -0.485018 -2.229938 -1.307950
max  1.527350  0.728047  1.501404


In [ ]:
format=lambda x: '%.2f' % x
df_map=frame['e'].map(format)
print(df_map)

Utah      -0.75
Ohio       0.47
Texas     -1.31
Oregon     1.50
Name: e, dtype: object


In [ ]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
print(frame)
sort1=frame.sort_values(by='b')
print(sort1)
sort2=frame.sort_values(by=['a','b'])
print(sort2)

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1
   b  a
2 -3  0
3  2  1
0  4  0
1  7  1
   b  a
2 -3  0
0  4  0
3  2  1
1  7  1


In [ ]:
obj = pd.Series([7, -5, 7, 3, 2, 0, 4])
def_obj=obj.rank()
print(def_obj)
def_asc=obj.rank(ascending=False,method='max')
print(def_asc)

0    6.5
1    1.0
2    6.5
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64
0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    3.0
dtype: float64


In [ ]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
'c': [-2, 5, 8, -2.5]})
rank=frame.rank(axis='columns')
print(rank)

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0


In [ ]:
obj = pd.Series(range(3), index=['a',  'b', 'c'])
print(obj.index.is_unique)

True


In [ ]:
data = {'Math': np.random.randint(50, 100, 5),
'Science': np.random.randint(50, 100, 5),
'English': np.random.randint(50, 100, 5),
'History': np.random.randint(50, 100, 5),
'Geography': np.random.randint(50, 100, 5)}
df = pd.DataFrame(data, index=['Student1', 'Student2', 'Student3', 'Student4', 'Student5'])
df

Math  Science  English  History  Geography
Student1    71       68       54       73         99
Student2    79       52       71       69         74
Student3    66       73       80       71         83
Student4    64       54       97       94         61
Student5    61       87       81       81         90

In [ ]:
df.rank()

Math  Science  English  History  Geography
Student1   4.0      3.0      1.0      3.0        5.0
Student2   5.0      1.0      2.0      1.0        2.0
Student3   3.0      4.0      3.0      2.0        3.0
Student4   2.0      2.0      5.0      5.0        1.0
Student5   1.0      5.0      4.0      4.0        4.0

In [ ]:
df.rank(ascending=False)

Math  Science  English  History  Geography
Student1   2.0      3.0      5.0      3.0        1.0
Student2   1.0      5.0      4.0      5.0        4.0
Student3   3.0      2.0      3.0      4.0        3.0
Student4   4.0      4.0      1.0      1.0        5.0
Student5   5.0      1.0      2.0      2.0        2.0

In [ ]:
df = pd.DataFrame({'Column1': [1, 2, np.nan, 4],
'Column2': [5, np.nan, 7, 8]})
print(df)

   Column1  Column2
0      1.0      5.0
1      2.0      NaN
2      NaN      7.0
3      4.0      8.0


In [ ]:
df.sum(axis=0)

Column1     7.0
Column2    20.0
dtype: float64

In [ ]:
df.sum(axis=1)

0     6.0
1     2.0
2     7.0
3    12.0
dtype: float64

In [ ]:
df.mean(axis='columns')

0    3.0
1    2.0
2    7.0
3    6.0
dtype: float64

In [ ]:
df.mean(axis='columns',skipna=False)

0    3.0
1    NaN
2    NaN
3    6.0
dtype: float64

In [ ]:
df.mean(axis='columns')

0    3.0
1    2.0
2    7.0
3    6.0
dtype: float64

In [ ]:
min_index=df.min()
max_index=df.max()
print(min_index)
print(max_index)

Column1    1.0
Column2    5.0
dtype: float64
Column1    4.0
Column2    8.0
dtype: float64


In [ ]:
df = pd.DataFrame({'A': [1, 2, 3, 4, 5],
'B': [5, 4, 3, 2, 1]})
cumsum_df=df.cumsum()
print(cumsum_df)

    A   B
0   1   5
1   3   9
2   6  12
3  10  14
4  15  15


In [ ]:
df.describe()

A         B
count  5.000000  5.000000
mean   3.000000  3.000000
std    1.581139  1.581139
min    1.000000  1.000000
25%    2.000000  2.000000
50%    3.000000  3.000000
75%    4.000000  4.000000
max    5.000000  5.000000

In [ ]:
df_non_numeric = pd.DataFrame({
'Name': ['Alice', 'Bob', 'Charlie', 'Bob'],
'City': ['New York', 'Los Angeles', 'Chicago', 'Alberta'],
'Country': ['USA', 'USA', 'USA', 'Canada']
})
summary=df_non_numeric.describe(include='object')
print(summary)

       Name      City Country
count     4         4       4
unique    3         4       2
top     Bob  New York     USA
freq      2         1       3


In [ ]:
data = {'A': [1, 2, 3, 4, 5],
'B': [5, 4, 3, 2, 1],
'C': [2, 3, 5, 1, 4]}
df = pd.DataFrame(data)
print(df)
print(df.corr())
print(df.cov())

   A  B  C
0  1  5  2
1  2  4  3
2  3  3  5
3  4  2  1
4  5  1  4
     A    B    C
A  1.0 -1.0  0.2
B -1.0  1.0 -0.2
C  0.2 -0.2  1.0
     A    B    C
A  2.5 -2.5  0.5
B -2.5  2.5 -0.5
C  0.5 -0.5  2.5


In [ ]:
value_counts=df['B'].value_counts()
print(value_counts)
is_present=3 in df['C'].values
print(is_present)

B
5    1
4    1
3    1
2    1
1    1
Name: count, dtype: int64
True


In [ ]:
is_present_multiple=df['A'].isin([2,4,6])
print(is_present_multiple)

0    False
1     True
2    False
3     True
4    False
Name: A, dtype: bool


In [ ]:
data = {'A': [1, 2, 3, 4, 5],
'B': [5, 4, 3, 2, 1],
'C': [2, 3, 5, 1, 4]}
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
# Get integer locations for requested labels
index_values = df.index.get_indexer(['b', 'e', 'f'])
print(index_values) # Output: [ 1 4 -1]

[ 1  4 -1]


In [ ]:
df = pd.DataFrame({
'col1': [1, 2, 3, 1, 2, 3, 4, 5],
'col2': [2, 3, 4, 2, 3, 4, 5, 6],
'col3': [3, 4, 5, 3, 4, 5, 6, 7]
})
result=df.apply(pd.value_counts).fillna(0)
print(result)

   col1  col2  col3
1   2.0   0.0   0.0
2   2.0   2.0   0.0
3   2.0   2.0   2.0
4   1.0   2.0   2.0
5   1.0   1.0   2.0
6   0.0   1.0   1.0
7   0.0   0.0   1.0


/tmp/ipython-input-133-2616727875.py:6: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result=df.apply(pd.value_counts).fillna(0)


In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'b', 'b', 'd'])
print(df)
print(df.index.is_unique)
print((df.index=='a').sum()>1)

          0         1         2
a -1.230253 -0.238820  0.721411
b -0.830936  0.730226  1.371679
b  0.881583 -0.162628 -0.799622
d -0.008436  0.646459 -0.417237
False
False
